feat: tag in config

diff --git a/templates/bridgehead b/templates/bridgehead
--- a/templates/bridgehead
+++ b/templates/bridgehead
@@ -29,7 +29,7 @@ main() {
             {%- endif %}
             if ! systemctl list-units &> /dev/null; then
                 echo "Systemd is not active. Skipping systemd setup."
-                sudo -u bridgehead TAG=$TAG ./bridgehead update
+                sudo -u bridgehead ./bridgehead update
             else
                 install_systemd
             fi
@@ -69,14 +69,13 @@ main() {
         update)
             docker image prune -f
             # TODO: Check if the bridgehead script changed and if so rerun
-            # TODO: Read tag from config
-            docker pull samply/rusthead:${TAG:-latest} &>/dev/null || echo "Failed to pull latest rusthead image. Using latest local image."
+            docker pull samply/rusthead:{{ conf.version_tag }} &>/dev/null || echo "Failed to pull latest rusthead image. Using latest local image."
             docker run --rm \
                 -v {{ config_dir }}:{{ config_dir }} \
                 -v /var/run/docker.sock:/var/run/docker.sock \
                 -e BRIDGEHEAD_CONFIG_PATH={{ config_dir }} \
                 -u "$(id -u bridgehead):$(id -g bridgehead)" \
-                samply/rusthead:${TAG:-latest} update
+                samply/rusthead:{{ conf.version_tag }} update
             ;;
         *)
             echo "Unknown bridgehead command '$@'"
